#spring.application.name=bms_backend
#spring.datasource.url=jdbc:mysql://localhost:3306/bms_db
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
spring.application.name=bms_backend

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Connect to MySQL running in Docker
spring.datasource.url=jdbc:mysql://localhost:3306/bms_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=paliparaniiidasmarinas@gmail.com
spring.mail.password=tvqw mwqo dajk nbcx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret=YjY5ZTY0NjY2OWVjZTA5YjE4ZDJjYmQxZTU4ZDU4YjE4ZDJjYmQxZTU4ZA==
jwt.access.exp=900000
jwt.refresh.exp=604800000

#textbee.api.url=http://localhost:8080/api/v1/sms/send
#textbee.api.url=https://api.textbee.dev/api/v1/gateway/devices
#textbee.api.key=1b140679-37bc-49b2-aa95-037a201cfdbe
#textbee.device.id=09152130431

semaphore.api.url=https://api.semaphore.co/api/v4/messages
semaphore.api.key=d5e5e941e7b672b282dabef46363bd56

#server.port=${PORT:8080}
#server.address=0.0.0.0
